let csrf='',profile=null;
const $=id=>document.getElementById(id);
const say=text=>{$('notice').textContent=text;};
async function api(path,method='GET',body){const r=await fetch(path,{method,credentials:'same-origin',headers:{'Content-Type':'application/json','X-NR-CSRF':csrf},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Error(data.detail||'Ошибка соединения');return data;}
async function refresh(){profile=await api('/me');csrf=profile.csrf;$('name').textContent=profile.name;$('disks').textContent=profile.disks;$('link').disabled=profile.linked;$('link').textContent=profile.linked?'Аккаунт привязан':'Привязать аккаунт';await catalog();}
async function catalog(){const data=await api('/catalog');$('catalog').replaceChildren();for(const p of data.packs){const card=document.createElement('div');card.className='pack';const detail=document.createElement('div'),title=document.createElement('h3'),desc=document.createElement('p'),button=document.createElement('button');title.textContent=p.name;desc.textContent=p.description;detail.append(title,desc);const owned=profile?.unlocks.includes(p.id);button.textContent=owned?'Открыто':p.kind==='arg'?'ARG':`${p.cost} диска`;button.disabled=owned||p.kind==='arg'||!profile;button.onclick=async()=>{try{button.disabled=true;await api('/packs/claim','POST',{pack_id:p.id});await refresh();say('Дата-пак сохранён навсегда.');}catch(e){say(e.message);button.disabled=false;}};card.append(detail,button);$('catalog').append(card);}}
$('puzzle').onsubmit=async e=>{e.preventDefault();try{const r=await api('/arg/submit','POST',{puzzle_id:'elara-001',answer:$('answer').value});say(r.solved?'Фрагмент восстановлен. Элара помнит.':'Сигнатура не совпадает.');await refresh();}catch(e){say(e.message);}};
$('link').onclick=async()=>{try{const r=await api('/oauth/start','POST',{});location.assign(r.url);}catch(e){say(e.message);}};
(async()=>{await catalog();try{await refresh();say('Защищённый канал восстановлен.');}catch{const tg=window.Telegram?.WebApp;if(!tg?.initData)return;tg.ready();tg.expand();try{const r=await api('/auth/telegram','POST',{init_data:tg.initData});csrf=r.csrf;await refresh();say('Личность подтверждена Telegram.');}catch(e){say(e.message);}}})();
